version: '3.9'

services:
    web:
        build: .
        networks:
            - maoge_hms_net
        container_name: maoge-hms-svelte
        ports: 
            - "80:3000"
        depends_on:
            - db
        

    db: 
        image: mysql
        container_name: maoge-hms-mysql
        restart: always
        volumes:
            - ./mysql/data:/var/lib/mysql 
            - ./mysql/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: maoge 
            MYSQL_USER: maoge
            MYSQL_PASSWORD: maoge
            MYSQL_DATABASE: maoge 
        networks:
            - maoge_hms_net
        

# volumes:
#     maoge-hms-data:
#         name: maoge-hms-data 
#         external: true

networks:   
    maoge_hms_net:
